name: PanIndex Release
on:
  release:
    types: [created]
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
   # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - uses: libsgh/PanIndex-release-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}